
unbind r
bind r source-file ~/.tmux.conf

# tmux's default prefix is c-b: conflicts with our vim config
# -> change this to c-t (t for tmux "mnemonic")
set -g prefix c-t

set -g mouse on

set -g status off
set -g pane-active-border-style fg=default

set-option -g set-titles on
set-option -g set-titles-string "#h | #S"

# -- quick tmux cheatsheet
# -- . tmux new -A -s <mysession>
#      start a new session or attach to an existing session named <mysession>
#    . tmux attach-session (or tmux a)  to attach to last session
#      (use -t <mysession> to attach to <mysession>)
#    . c-t d to detach from the current session
#    . tmux list-sessions  (or tmux ls) to list all sessions
#    . : split-window -h (c-t %) and : split-window -v (c-t ")
#      to split tmux's pane horizontally or vertically
#
#    note: keep in mind we changed the prefix from the default c-b to c-t above

# -- tmux plugin manager
# -- https://github.com/tmux-plugins/tpm
# -- git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'

# -- ease up navigation between panes
# -- ie. between vim windows and tmux panes using simply c-arrows
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @vim_navigator_mapping_up    "c-up"
set -g @vim_navigator_mapping_down  "c-down"
set -g @vim_navigator_mapping_left  "c-left"
set -g @vim_navigator_mapping_right "c-right"

# -- restore tmux environment after system restart.
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'

